parking/protected/models/Platnosc.php
<?php

/**
 * This is the model class for table "Platnosc".
 *
 * The followings are the available columns in table 'Platnosc':
 * @property integer $ID_platnosc
 * @property integer $Status
 * @property float $Kwota
 * @property integer $Data
 * @property integer $ID_user
 *
 * The followings are the available model relations:
 * @property User $iDUser
 */
class Platnosc extends CActiveRecord
{
    
    public static $PLATNOSC_STATUS_ZAKONCZONA = 1;
    public static $PLATNOSC_STATUS_ROZPOCZETA = 0;
    public static $PLATNOSC_STATUS_NIEPOPRAWNA = -1;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'Platnosc';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('Status, Kwota, Data, ID_user', 'required'),
			array('Status, Data, ID_user', 'numerical', 'integerOnly'=>true),
                        array('Kwota', 'type', 'type'=>'float'),
                        array('Kwota', 'match', 'pattern'=>'/^\d+(\.\d{2})?$/'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('ID_platnosc, Status, Kwota, Data, ID_user', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'iDUser' => array(self::BELONGS_TO, 'User', 'ID_user'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'ID_platnosc' => 'Id Platnosc',
			'Status' => 'Status',
			'Kwota' => 'Kwota',
			'Data' => 'Data',
			'ID_user' => 'Telefon użytkownika',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search($this_user = false)
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('ID_platnosc',$this->ID_platnosc);
		$criteria->compare('Status',$this->Status);
		$criteria->compare('Kwota',$this->Kwota);
		$criteria->compare('Data',$this->Data);
		
                if($this_user){
                    $criteria->compare('ID_user',Yii::app()->user->getId());
                } else {
                    $criteria->compare('ID_user',$this->ID_user);
                }

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Platnosc the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        public function getStatusString(){
            if($this->Status == static::$PLATNOSC_STATUS_ZAKONCZONA){
                return "Zakończona";
            } else if($this->Status == static::$PLATNOSC_STATUS_ROZPOCZETA){
                return "Rozpoczęta";
            } if($this->Status == static::$PLATNOSC_STATUS_NIEPOPRAWNA){
                return "Niepoprawna";
            }
        }
}

parking/protected/controllers/PlatnoscController.php
<?php

class PlatnoscController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules() {
        return array(
            array('allow',
                'actions'=>array('history','zaplac'),
                'users' => array('@'),
            ),
            array('allow',
                'expression' => 'Yii::app()->user->isAdmin==1',
                'users'=>array('@'),
            ),
            array('deny',
                'users' => array('*'),
            ),
        );
    }

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Platnosc;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Platnosc']))
		{
			$model->attributes=$_POST['Platnosc'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
        
        public function actionZaplac()
	{
		$model=new Platnosc;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Platnosc']))
		{
			$model->attributes=$_POST['Platnosc'];
                        $model->Status = Platnosc::$PLATNOSC_STATUS_ZAKONCZONA;
                        $model->Data = time();
                        $model->ID_user = Yii::app()->user->getId();
			if($model->save())
				$this->redirect('/index.php/site/page?view=settings');
		}

		$this->render('zaplac',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Platnosc']))
		{
			$model->attributes=$_POST['Platnosc'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Platnosc');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Platnosc('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Platnosc']))
			$model->attributes=$_GET['Platnosc'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
        
        public function actionHistory()
	{
		$model=new Platnosc('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Platnosc']))
			$model->attributes=$_GET['Platnosc'];

		$this->render('history',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Platnosc the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Platnosc::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Platnosc $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='platnosc-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

parking/protected/views/platnosc/_form.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'platnosc-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Pola oznaczone <span class="required" style="color:red;">*</span> są wymagane.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'Status'); ?>
		<?php echo $form->textField($model,'Status'); ?>
		<?php echo $form->error($model,'Status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'Kwota'); ?>
		<?php echo $form->textField($model,'Kwota'); ?>
		<?php echo $form->error($model,'Kwota'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'Data'); ?>
		<?php echo $form->textField($model,'Data'); ?>
		<?php echo $form->error($model,'Data'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Utwórz' : 'Zapisz'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

parking/protected/views/platnosc/_search.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'ID_platnosc'); ?>
		<?php echo $form->textField($model,'ID_platnosc'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Status'); ?>
		<?php echo $form->textField($model,'Status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Kwota'); ?>
		<?php echo $form->textField($model,'Kwota'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Data'); ?>
		<?php echo $form->textField($model,'Data'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ID_rezerwacja'); ?>
		<?php echo $form->textField($model,'ID_rezerwacja'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

parking/protected/views/platnosc/_view.php
<?php
/* @var $this PlatnoscController */
/* @var $data Platnosc */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('ID_platnosc')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->ID_platnosc), array('view', 'id'=>$data->ID_platnosc)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Status')); ?>:</b>
	<?php echo CHtml::encode($data->Status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Kwota')); ?>:</b>
	<?php echo CHtml::encode($data->Kwota); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Data')); ?>:</b>
	<?php echo CHtml::encode($data->Data); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ID_rezerwacja')); ?>:</b>
	<?php echo CHtml::encode($data->ID_rezerwacja); ?>
	<br />


</div>

parking/protected/views/platnosc/admin.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */

$this->breadcrumbs=array(
	'Panel administracyjny'=>array('/site/page?view=admin'),
	'Zarządzaj płatnościami',
);



?>

<h1>Zarządzaj płatnościami</h1>


<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'platnosc-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
                array(
                    'name'=>'ID_user',
                    'value'=>'$data->iDUser->Telefon'
                ),
                array(
                'name'=>'Kwota',
                'value'=>'$data->Kwota." PLN"'
                ),
		array(
                'name'=>'Status',
                'value'=>'$data->getStatusString()'
                ),
		'Data',
                
		array(
                    'header'=>'Akcja',
                    'class'=>'CButtonColumn',
                    'template'=>'{update} {delete}',
                    ),
	),
)); ?>

parking/protected/views/platnosc/create.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */

$this->breadcrumbs=array(
        'Panel administracyjny'=>array('/site/page?view=admin'),
	'Utwórz płatność',
);

$this->menu=array(
	array('label'=>'Zarządzaj płatnościami', 'url'=>array('admin')),
);
?>

<h1>Utwórz płatność</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

parking/protected/views/platnosc/history.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */

$this->breadcrumbs=array(
	'Ustawienia konta'=>array('/site/page?view=settings'),
	'Historia płatności',
);

$this->menu=array(
	array('label'=>'Doładuj konto', 'url'=>array('/platnosc/zaplac')),
);


?>

<h1>Historia płatności</h1>


<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'platnosc-grid',
	'dataProvider'=>$model->search(true),
	'filter'=>$model,
	'columns'=>array(
                array(
                'name'=>'Data',
                'value'=>'date("Y-m-d H:i:s",$data->Data)'
                ),
		array(
                'name'=>'Kwota',
                'value'=>'$data->Kwota." PLN"'
                ),
                array(
                'name'=>'Status',
                'value'=>'$data->getStatusString()'
                ),
	),
)); ?>

parking/protected/views/platnosc/index.php
<?php
/* @var $this PlatnoscController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Platnoscs',
);

$this->menu=array(
	array('label'=>'Create Platnosc', 'url'=>array('create')),
	array('label'=>'Manage Platnosc', 'url'=>array('admin')),
);
?>

<h1>Platnoscs</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

parking/protected/views/platnosc/update.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */

$this->breadcrumbs=array(
        'Panel administracyjny'=>array('/site/page?view=admin'),
	'Zarządzaj płatnościami'=>array('admin'),
	'Aktualizuj',
);

$this->menu=array(
	array('label'=>'Utwórz Płatności', 'url'=>array('create')),
	array('label'=>'Zarządzaj Płatnościami', 'url'=>array('admin')),
);
?>

<h1>Aktualizuj Płatności <?php echo $model->ID_platnosc; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

parking/protected/views/platnosc/view.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */

$this->breadcrumbs=array(
	'Platnoscs'=>array('index'),
	$model->ID_platnosc,
);

$this->menu=array(
	array('label'=>'List Platnosc', 'url'=>array('index')),
	array('label'=>'Create Platnosc', 'url'=>array('create')),
	array('label'=>'Update Platnosc', 'url'=>array('update', 'id'=>$model->ID_platnosc)),
	array('label'=>'Delete Platnosc', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->ID_platnosc),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Platnosc', 'url'=>array('admin')),
);
?>

<h1>View Platnosc #<?php echo $model->ID_platnosc; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'ID_platnosc',
		'Status',
		'Kwota',
		'Data',
		'ID_rezerwacja',
	),
)); ?>

parking/protected/views/platnosc/zaplac.php
<?php
/* @var $this PlatnoscController */
/* @var $model Platnosc */


$this->breadcrumbs=array(
	'Ustawienia konta'=>array('/site/page?view=settings'),
        'Doładuj konto'
);
?>

<h1>Doładuj konto</h1>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'platnosc-form',
	'enableAjaxValidation'=>false,
)); ?>


	<?php echo $form->errorSummary($model); ?>


	<div class="row">
		<?php echo $form->labelEx($model,'Kwota'); ?>
		<?php echo $form->textField($model,'Kwota'); ?> PLN
		<?php echo $form->error($model,'Kwota'); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton('Doładuj konto'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->